### PR TITLE
Update the install_requires after the move from qrcode to segno.

### PR DESCRIPTION
**Pull request by mapreri**

### CODE REVIEW

**Comment by fharbe** [comment]
Thanks for your PR @mapreri! :+1: 

I wanted to open the same PR, because currently django-qr-code does not work anymore (because of the wrong dependencies in the setup.py). Would appreciate a quick merge! :wink: 

/cc @philippe-docourt

**Comment by philippe-docourt** [comment]
Thank you guys! I tested the new release in a real project and it seemed to work... except I already had segno in my virtual env. Oups!

**Comment by philippe-docourt** [comment]
I just pushed a new release 2.0.1 to PyPi!

**Comment by fharbe** [comment]
Thank you for the quick new release! @philippe-docourt

**Pull request merged**
