### PR TITLE
Change django.utils.six to six

### PR DESCRIPTION
**Pull request by subinabid**
To Support Django3
Django3 dropped support for Python2
This requires 2 modifications
1. django.utils.six - switch to six
2 . django.utils.decorators.available_attrs()  - alternate to be explored

This commit takes care of Sl#1

### CODE REVIEW

**Comment by philippe-docourt** [comment]
@subinabid Unfortunately, removing the caching feature is not a proper way to ensure compatibility with Django 3.0. It's just a feature removal.

**Comment by philippe-docourt** [comment]
I'm working on a better way to handle compatibility with Django 3.0.

**Comment by subinabid** [comment]
@philippe-docourt that was only a quick fix. Thanks for taking this up

**Comment by philippe-docourt** [comment]
Release 1.2 solves the compatibility with Django 3.0.

**Pull request closed without merging**
